### PR TITLE
add Swig3.0 to minimum requirements

### PR DESCRIPTION
**Pull request by 0shimax**
The minimum requirement for import was insufficient.
That's why I added "Swig 3.0".
Thanks.

### CODE REVIEW

**Comment by CaoZhongZ** [comment]
Oh, thanks! Actually it should be beyond version 3.0.9. Thank you!

**Comment by CaoZhongZ** [comment]
Could you please change it to 3.0.9 then I'll merge this pull request. Thanks

**Comment by 0shimax** [comment]
@4pao 
Thank you for the reply. I have done.
Pls merge PR.

Thanks

**Review by CaoZhongZ — APPROVED** [review]

**Comment by uyongw** [comment]
Add SWIG 3.0 to requirements

**Pull request merged**
